### ISSUE TITLE
Does not work with Apache Maven 3.1

### ISSUE THREAD

**Issue by talios** [javafx-maven-plugin/javafx-maven-plugin#32]
Apache Maven 3.1 has just been released ( altho the release isn't officially published yet ) which makes a change from using Sonatype Aether to using Eclipse Aether, which incurs package renames, and a few API changes.

    [ERROR] Failed to execute goal com.zenjava:javafx-maven-plugin:1.5:build-jar
      (build-jar) on project norrellfx: Execution build-jar of goal
      com.zenjava:javafx-maven-plugin:1.5:build-jar failed: An API incompatibility was
     encountered while executing com.zenjava:javafx-maven-plugin:1.5:build-jar:
       java.lang.NoSuchMethodError:
     org.apache.maven.execution.MavenSession.getRepositorySession()Lorg/sonatype/aether/RepositorySystemSession;

**Comment by emont01** [comment]
I hope this helps anyone still having this problem,here is an example of how to specify the correct mojo-executor version taken from [stackoverflow answer](https://stackoverflow.com/a/20501951/606826):

```xml
<build>
    <plugins>
        <plugin>
            <groupId>com.zenjava</groupId>
            <artifactId>javafx-maven-plugin</artifactId>
            <version>2.0</version>
            <configuration>
                <mainClass>net.jalbright.scratch.App</mainClass>
            </configuration>
            <dependencies>
                <dependency>
                    <groupId>org.twdata.maven</groupId>
                    <artifactId>mojo-executor</artifactId>
                    <version>2.1.0</version>
                </dependency>
            </dependencies>
        </plugin>
    </plugins>
</build>
```

**Comment by FibreFoX** [comment]
Closed, because its already merged.
